name: Unit Tests

on:
  push:
    branches:
      - cereed4/working&such
  pull_request:
    branches: [cereed4/working&such]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test